### PR TITLE
Update to allow upload of SPIFFS as well

### PR DESCRIPTION
**Pull request by dushyantahuja**
Based on code from https://github.com/lbernstone/asyncUpdate/blob/master/AsyncUpdate.ino#L42

### CODE REVIEW

**Comment by ayushsharma82** [comment]
Nice Addition. I will alter the UI a bit and merge this.

**Comment by dushyantahuja** [comment]
Just wanted to check if you're going to merge this. Thanks.

**Comment by ayushsharma82** [comment]
@dushyantahuja Done! :D I was quite busy with my stuff. Thanks for the reminder.

**Comment by dushyantahuja** [comment]
No problems at all. Thanks for merging. Have a great day

**Pull request merged**
