### PR TITLE
Restart fix and simplify

### PR DESCRIPTION
**Pull request by sui77**
Was looking into the restart issue #44 ... and came up with thinking there is no point in having the loop() method. Might be some kind of best practice but on the other hand KISS and YAGNI. And I also think this is the perfect answer to #56 

Then my ESP32 perfectly resets with `ESP.restart();` - so I don't know for sure if the used suicide method is obsolete or my ESP32 is different?

### CODE REVIEW

**Comment by ayushsharma82** [comment]
Yeah. I think the current restart method is obsolete. Let's not break the loop functionality for people upgrading the library ( keep an empty loop function ). Please add a compiler warning in this release, We will delete it in future.

**Comment by ayushsharma82** [comment]
and @sui77 , With this method, does your webpage show success? ( Just making sure the http response is sent back to the webpage before restart. )

**Comment by sui77** [comment]
- Added a compiler warning (did I do it right? never done that before).
- Upload work flawless for me, 1-2s after 100% I get the `✅ OTA Success` and it definitely restarts.

**Comment by ayushsharma82** [comment]
Merged :)

**Comment by mindrunner** [comment]
For me, this does not work as expected. With this change applied, the web server response never arrives, but the connection just drops. (fw-update and restart seems successful tho)

With the `loop` approach, the update happens, the servers response will be sent and then the device restarts. 

Feels cleaner to me.

**Pull request merged**
